_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.11.4
        t:
            "1":
                - 55
                - 95
                - 105
            "2":
                - 55
                - 95
                - 105
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.11.4
            "5": 0.19.6
            "8":
                - 5
                - 9
            "12": 0.19.6
            "13": darwin-arm64
api_version:
    value: "1.0"
model:
    value: o3-mini-2025-01-31
